# Generated by Django 2.2 on 2019-05-02 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_renting'),
    ]

    operations = [
        migrations.RenameField(
            model_name='renting',
            old_name='total_price',
            new_name='time_use',
        ),
        migrations.AddField(
            model_name='renting',
            name='type_use',
            field=models.CharField(choices=[('0', 'Hour'), ('1', 'Day'), ('2', 'Week'), ('3', 'Month'), ('4', 'Up tp car owner')], default='4', max_length=1),
        ),
    ]
