# Generated by Django 2.2 on 2019-05-03 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20190502_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='renting',
            name='time_use',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='renting',
            name='type_use',
            field=models.CharField(choices=[('0', 'Hour'), ('1', 'Day'), ('2', 'Week'), ('3', 'Month'), ('4', 'Up to car owner')], default='4', max_length=1),
        ),
    ]
