# Generated by Django 2.2 on 2019-05-03 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20190503_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='renting',
            name='license_image',
            field=models.ImageField(default='license.jpg', upload_to='license_pic'),
        ),
    ]
