# Generated by Django 2.2 on 2019-05-01 14:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20190430_2157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='date_posted',
        ),
        migrations.AddField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
