# Generated by Django 2.2 on 2019-05-01 16:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20190501_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
