# Generated by Django 2.2 on 2019-05-05 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_contract'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('1', 'ก่อกวน'), ('2', 'ทำผิดสัญญา'), ('3', 'ข้อมูลยานพาหนะไม่ตรงกับSpecificationที่ตกลงเอาไว้'), ('4', 'ข้อมูลส่วนตัวไม่ตรงกับความเป็นจริง'), ('5', 'อื่น')], max_length=1)),
                ('text', models.CharField(blank=True, max_length=255, null=True)),
                ('reported', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.Car')),
            ],
        ),
    ]
