# Generated by Django 2.2 on 2019-05-07 08:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0007_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='renting',
            name='time_use',
            field=models.DurationField(null=True),
        ),
    ]
